server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    #设置注册的地址 http://ip:port/eureka
    #ip：服务注册与发现中心的ip
    #port: 服务注册与发现中心的端口
    #eureka:固定写法
    service-url:
      defaultzone: http://localhost:8761/eureka